### PR TITLE
hub-stack-deploy unable to download state from pod

### PR DESCRIPTION
**Pull request by igorlysak**
Need to review so this fix will not impact some other cases.

Now both state and elaborate files pass to `hub explain` after `hub stack deploy`

### CODE REVIEW

**Comment by arkadijs** [comment]
See `hub explain -h` for correct syntax.

**Review by akranga — CHANGES_REQUESTED** [review]
I believe this change is incomplete... Another part of the change required here: https://github.com/agilestacks/hub-extensions/blob/master/profiles/pod/hubw#L37

**Comment by arkadijs** [comment]
1. `elaborate` file is not strictly necessary for correct operation of `explain` (in context of `show`).
2. State file download from pod should also handle corner cases when there is no local state file at all; or there is no state file specified (defaults to `hub.yaml.state`).

**Comment by igorlysak** [comment]
@akranga @arkadijs guys could you please review latest commit. It should solve problem regarding download of state file from toolbox container when `hub stack deploy` finish work

**Review by arkadijs — CHANGES_REQUESTED** [review]
1. What if `HUB_STATE="s3://883577250959.superhub.io/eks-1.qdxh.superhub.io/hub/qdx_infra/hub.state"`?
2. Hub CLI won't write under `.hub/` until it is a CWD.

**Comment by igorlysak** [comment]
> What if HUB_STATE="s3://883577250959.superhub.io/eks-1.qdxh.superhub.io/hub/qdx_infra/hub.state"?

I thought about this. As far as I understand hub CLI supports store of state and elaborate files under gcp and azure storages as well. If so then I see no reason to download state from cloud. But I assume that whatever happens state file should be inside container or am I wrong?

> Hub CLI won't write under .hub/ until it is a CWD.

So default location for state file is CWD?

**Review by arkadijs — APPROVED** [review]

**Pull request merged**
